name: Docker Image CI

on:
  workflow_dispatch:

  push:

  pull_request:

jobs:

  make_list:

    runs-on: ubuntu-latest

    container:
      image: jotego/jtdock:jtutil
      credentials:
        username: jotego
        password: ${{ secrets.DOCKER_LOGIN }}

    steps:
      - name: check out
        uses: actions/checkout@v2
        with:
          repository: jotego/jtbubl
          path: git
      - name: get submodules
        run: cd git; git submodule update --init --recursive --depth 1
      - name: list repo
        run: find .
      - name: compile
        run: source $JTUTIL/bin/jtutil.sh; jtcore bubl -mr

