name: Docker Image CI

on:
  workflow_dispatch:

  push:

  pull_request:

jobs:

  make_list:

    runs-on: ubuntu-latest

    container:
      image: jotego/jtdock:q17-go
      credentials:
        username: jotego
        password: ${{ secrets.DOCKER_LOGIN }}

    steps:
      - name: check out
        uses: actions/checkout@v2
        with:
          repository: jotego/jtbubl
          path: core
      # - name: check out
      #   uses: actions/checkout@v2
      #   with:
      #     repository: jotego/jtutil
      - name: list repo
        run: cd core; git submodule init; git submodule update; find .
