name: Docker Image CI

on:
  push:

  pull_request:

jobs:

  make_list:

    runs-on: ubuntu-latest

    container:
      image: jotego/jtdock:q17-go
      credentials:
        username: jotego
        password: ${{ secrets.DOCKER_LOGIN }}

    steps:
      - name: check out
        uses: actions/checkout@v2
        with:
          repository: jotego/jtbubil
      - name: list repo
        run: find .

